openapi: 3.0.3
info:
  title: Travel Planner API
  version: 1.0.0
  description: API for managing trips, accommodations, activities, destinations, and users.
servers:
  - url: http://localhost:3000
    description: Local development servers
  - url: https://task-api-1-0j99.onrender.com/
    description: Production sever on render
paths:
  /accommodations:
    $ref: paths/accommodations.yaml
  /accommodations/{id}:
    $ref: paths/accommodations_{id}.yaml
  /activities:
    $ref: paths/activities.yaml
  /activities/{id}:
    $ref: paths/activities_{id}.yaml
  /destinations:
    $ref: paths/destinations.yaml
  /destinations/{id}:
    $ref: paths/destinations_{id}.yaml
  /trips:
    $ref: paths/trips.yaml
  /trips/{id}:
    $ref: paths/trips_{id}.yaml
  /users:
    $ref: paths/users.yaml
  /users/{id}:
    $ref: paths/users_{id}.yaml
